[build]
builder = "nixpacks"
buildCommand = "pnpm i --no-frozen-lockfile && pnpm --filter @workspace/api-server run build"

[deploy]
startCommand = "node artifacts/api-server/dist/index.mjs"

[build.nixpacksPlan.phases.install]
cmds = ["pnpm i --no-frozen-lockfile"]
