kind = "mobile"
previewPath = "/"
title = "ORBIT-MESH"
version = "1.0.0"
id = "artifacts/orbit-mesh"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 22381

[services.development]
run = "pnpm --filter @workspace/orbit-mesh run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/orbit-mesh", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/orbit-mesh", "run", "serve" ]

[services.env]
PORT = "22381"
BASE_PATH = "/"
