[phases.setup]
nixPkgs = ["nodejs_18", "nodePackages.pnpm"]

[phases.install]
cmds = ["cd /app && pnpm i --no-frozen-lockfile"]

[phases.build]
cmds = ["cd /app/artifacts/orbit-mesh && node scripts/build.js"]

[start]
cmd = "cd /app/artifacts/orbit-mesh && node server/serve.js"
